language: node_js

node_js:
      - 8

cache:
      directories:
            - node_modules

notifications:
      email:
            recipients:
                  - bstenm@hotmail.com
            on_success: change
            on_failure: change

install:
      - yarn add coveralls

script:
      - yarn test-client --coverage --coverageReporters=text-lcov | coveralls
      - yarn build-client

deploy:
      provider: s3
      access_key_id: AKIAJUERDPZC5WLZK7OA
      bucket: ico-contributions-visualizer-client
      local_dir: build
      skip_cleanup: true
      secret_access_key:
            secure: H6zH3JMEoUiZgO1babwu8QdaAnbVPiXXMi3mE1fKDgGojVpCqJkWlBL5Ioow0dACXLFYDczUECKY1lRl+t/ZtGyoT5pPKO8mcdaE06+GavheoRECwoW609OcNDVQ3RvhZG2hnwfYVdiY6IVJRUaYXPZay1WyW6X7Z7Ll2Jt+TgZlwcKtrAlR4CUOwbnWZqvyQ9QvPJiJ5mapYD8nBLOOTVcgjwoLfokySPvEJjC8/RbeA3kxlXgXF3PVTk2ffBzqIRJ41Falclr9QHKizX3yMUwjh7B/cASSZcGBFPJEnyn27F0KFNaQCDJTCrkRUZf5BcnocjR+NxWbrHVri3OC3jHcxMHZdn9S1RAYScA3HS6cnhB5pTEmQVM7DbK/oEzGj5lEUuZHcE5NtuTB8WGF9aHst2flhdNPy75cLAvWLL76MbLig6+SVH+OB62fFNuQDTVWuJwxJFX6S5liDjzvf1xQTv9Z6ieUivr1T5pv65mETozTEWhbBs/9TPdZ014pI7TSrM5fcvJGfrIgf9Z41enio+etlb5cqWqNEBwSE8wczDu2SFucGc0lOhIHbAn+jsuCKL1qNFJ6mktJwEbrUOnpahdq8LrccvHuKeneWUOCxj/Y5mlb/HX0pYzQ+EdO1s13bKSQVIio/uo/n3JfU3MmcyJyGcXr3lTVDwZQkr8=

deploy:
      provider: heroku
      app: ico-contributions-visualizer
      api_key:
            secure: XcgWrKaAckxdNVBLes7LlDVZDTtFwNb1Qs52AM0kmR1XJ12y5BKDJfkxrwmJVEMPM/hplncDlfBou24UOlWgaIwn5CczPNmvOoeX+VKsqpQIDoeF0c4SMpaUwlua2VO+Fq95eSfnI1SinCxGWo6Yk1pUzaX356DN9PkTlwVmVu6VRx1t20VnDxIPFo0I1yhvMEFc1bI+eqSkNkMsfDuMdI4v9Ktud9ezKKlg+t9N4cib5dyQ8FwnCxKxTt2ZgbSrLf9YMFEmUkL/MPVjW+ulHWqTnxPXD50gUzXO25uF4om6tT82/5pJNB+qEJjXYcEiEH1X74xqjbk36q+pskzq5lYmVP5CvGDUK4irx1dRFIJsBVLANlnJomLwrWvGh6f98gXQSkh+R1OHnrBvdj3P66L/ag+KsUJRX7M/CBb/yzs60EM8EIE2cxVToQVKoHUNFBEl/SyzaNeAmNlZ5kPR8zkmnlu3KCgmk8FP1cz0HYLlB1rhQvTSn8fw8YTAsvidRBbwu5FGUWznwHUXwt5FpoxhSZrO0i9oPUOoSg7GOdFSGBgkJa36Xm8C9SeaUgVvNhRgSxvn5fPElD0pAYfw/LSGhpy/nEWCJBf+GxCdAHlMSLYznFG++0+zWbtj0FFLkHUmrd0+SSivK2SqwetDg0BIcYM6lT1/zGnG7D7pB8E=
